dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint
  options:
    config-data:
      line-length: disable

platforms:
  - name: bullseye
    box: debian/stretch64
#testing64

provisioner:
  name: ansible
  log: True
  connection_options:
    ansible_become: True
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0002
  inventory:
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3"
  config_options:
    defaults:
      ansible_managed: "This file is managed by Ansible, edit it in git!"
      stdout_callback: yaml
      retry_files_enabled: False
    diff:
      always: True

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
